version: "3.8"

services:
  gateway:
    image: ghcr.io/grafbase/grafbase
    container_name: gateway
    networks:
      - test
    ports:
      - 4000:4000
    depends_on:
      users:
        condition: service_healthy
      pandas:
        condition: service_healthy
      inventory:
        condition: service_healthy
      products:
        condition: service_healthy
      reviews:
        condition: service_healthy
    volumes:
      - type: bind
        source: federation-v2/gateways/grafbase/supergraph.graphql
        target: /dist/schema.graphql
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-f",
          "-X",
          "POST",
          "-H",
          "Content-type: application/json",
          "http://localhost:4000/graphql",
          "--data-raw",
          '{"query": "query { __typename }"}',
        ]
      interval: 3s
      timeout: 5s
      retries: 10
    deploy:
      resources:
        limits:
          cpus: ${CPU_LIMIT:-1}
          memory: ${MEM_LIMIT:-1gb}
networks:
  test:
    name: test-v2
